package com.main.mywasabi.Bot;

import java.util.ArrayList;

public class Comment {
    protected ArrayList<String> ai = new ArrayList<>();

    public Comment(){
        ai = new ArrayList<>();
        addComment();
    }

    public ArrayList<String> getAi() {
        return ai;
    }

    public void setAi(ArrayList<String> ai) {
        this.ai = ai;
    }

    public void addNewComment(String newComment){
        this.ai.add(newComment);
    }

    public void addComment(){
        this.ai.add("hahahahahahahahahahahha XXD XXDDD XXXDDDD!!!");
        this.ai.add("Tähän parempi ois et pakko heistaa ku sieltä päin tuulee");
        this.ai.add("painu helvettiin");
        this.ai.add("mä oon jo siel");
        this.ai.add("Mitä pahaa niissä on 👿");
        this.ai.add("Herranjumala. Sun kielioppitaito on aivan helvetin epäkunnioittavaa.");
        this.ai.add("pelle");
        this.ai.add("Sä oot se koko sirkus😊");
        this.ai.add("suksi vittuun");
        this.ai.add("Anna kartta🥰");
        this.ai.add("sähä tän paska alotit");
        this.ai.add(":DD");
        this.ai.add("Vastaa");
        this.ai.add("Ai Miks etsitkö poikaystävää");
        this.ai.add("haista paska");
        this.ai.add("ei kannata paskoo vasta tuulee");
        this.ai.add("venaa ku poliisit kuulee.");
        this.ai.add("kuka kysy");
        this.ai.add("mä vastasin et ei tarvi kysyy");
        this.ai.add("pakko haistaa ku sieltä päi tuulee");
        this.ai.add("XD 😆");
        this.ai.add("olipas kovanluokan servaus");
        this.ai.add("Hullu paljon työtä tekee, viisas pääsee vähemmällä. ");
        this.ai.add("Yksi peruna kerrallaan. ");
        this.ai.add("Ei kysyvä tieltä eksy. ");
        this.ai.add("Työ ei lopu tekemällä. ");
        this.ai.add("Aloittamista vaille valmis. Löytyykö vapaaehtoisia aloittamaan?");
        this.ai.add("Mennä perse edellä puuhun. ");
        this.ai.add("Mittaa kahdesti ja sahaa yhdesti. Liittyy edelliseen.");
        this.ai.add("Hyvin suunniteltu on puoliksi tehty. Jälleen samalla asialla.");
        this.ai.add("Hyvin suunniteltu, kokonaan tekemättä. Niin, pelkkä suunnittelu ei tietysti yksinään riitä.");
        this.ai.add("Ei siinä kauaa mene, kun töitä tekee. Voi vähän ärsyttää – mutta usein on niin, että homma hoituu, kun siihen ryhtyy.");
        this.ai.add("Kyllä hätä keinot keksii. Joskus pieni paine auttaa ratkomaan ongelmia.");
        this.ai.add("Pakko on paras muusa. Liittyy edelliseen.");
        this.ai.add("Älä jätä huomiseksi sitä, minkä voit tehdä jo tänään. Edelleen: joskus pitää vain ryhtyä.");
        this.ai.add("Miksi tehdä tänään jotain, minkä voi jättää huomennakin tekemättä. ");
        this.ai.add("Viikon kestää vaikka aidan seipäänä. ");
        this.ai.add("Työ tekijäänsä opettaa. ");
        this.ai.add("Hommat on levällään kuin Jokisen eväät. ");
        this.ai.add("Välillä näin on. ");
        this.ai.add("Ei niin pientä ojaa, ettei sinne oma lehmä mahtuisi. ");
        this.ai.add("Rohkea rokan syö. Rohkeus auttaa yksilöitä ja organisaatioita kasvamaan.");
        this.ai.add("Minkä taakseen jättää, sen edestään löytää. ");
        this.ai.add("Oppia ikä kaikki. ");
        this.ai.add("Jatkuvan oppimisen asialla!");
        this.ai.add("Ei kukaan ole seppä syntyessään. ");
        this.ai.add("Osaaminen kehittyy läpi elämän, ja uran alussa asenne paikkaa kokemuksen puutetta.");
        this.ai.add("Kukas se kissan hännän nostaa, ellei kissa itse. ");
        this.ai.add("Ei makaavan kissan suuhun hiiri tule. ");
        this.ai.add("Jos jotakin haluaa, on yleensä tehtävä töitä sen eteen.");
        this.ai.add("Luulo ei ole tiedon väärti. ");
        this.ai.add("Faktat kunniaan.");
        this.ai.add("Mitä useampi kokki, sitä huonompi soppa. ");
        this.ai.add("vähemmän on enemmän.");
        this.ai.add("Alku aina hankalaa, lopussa kiitos seisoo. Usein aloittaminen takkuaa, mutta lopulta tehty työ palkitsee.");
        this.ai.add("Hiljaa hyvä tulee. Joskus kiire ja sählääminen vain tekevät työstä tehottomampaa ja stressaavampaa.");
        this.ai.add("Ottaa itseään niskasta kiinni. Välillä tarpeen, joskaan kaikki asiat eivät ole kiinni itsestä.");
        this.ai.add("Palkka juoksee, minä en.");
        this.ai.add("Jos tunnet työniloa, istu hetkeksi ja odota, että se menee pois.");
        this.ai.add("Työ on sarja nälän aiheuttamia pakkoliikkeitä.");
        this.ai.add("Kyllä hyvälle tyypille aina työtä löytyy tai kyllä työtä tekevälle riittää. ");
        this.ai.add("Miten määritellään hyvä tyyppi? ");
        this.ai.add("Onko työllistyminen todella vain siitä kiinni? ");
        this.ai.add("Riittääkö kaikille töitä? ");
        this.ai.add("No, ei valitettavasti. ");
        this.ai.add("Kyllä tekevälle työtä löytyy, jos on oikea aika, paikka ja taloussuhdanne sekä osaamisen kysyntä ja tarjonta kohtaavat.");
        this.ai.add("Kova duuni on rahaa, lauloi Meiju Suvas. ");
        this.ai.add("Kova duuni on joillekin rahaa.");
        this.ai.add("Kenen leipää syöt, sen lauluja laulat. ");
        this.ai.add("Ahkeruus kovankin onnen voittaa. ");
        this.ai.add("Hyvät lähtökohdat voittavat.");
        this.ai.add("Ei leikki leipää tuo. ");
        this.ai.add("Ensin työ, sitten huvi. ");
        this.ai.add("Entä jos se työkin olisi tosiaan mukavaa? ");
        this.ai.add("Välillä työ, välillä huvi.");
        this.ai.add("Itku pitkästä ilosta. ");
        this.ai.add("Ura pitkästä ilosta.");
        this.ai.add("Haudassa ehtii levätä. ");
        this.ai.add("Lepää arjessa, sillä haudassa se on liian myöhäistä.");
        this.ai.add("Kylmä kahvi kaunistaa. ");
        this.ai.add("Ansaitset tauollasi kuumaa kahvia, ellei kyse ole hellepäivän jääkahvista.");
        this.ai.add("Kuuma kahvi kannustaa.");
        this.ai.add("Puhuminen hopeaa, vaikeneminen kultaa. ");
        this.ai.add("Puhuminen ja kuunteleminen hopeaa, niiden yhdistelmä kultaa.");
        this.ai.add("Hiki laiskan syödessä, kylmä työtä tehdessä. ");
        this.ai.add("Hiki tai kylmä työtä tehdessä, tärkeintä on lopputulos.");
        this.ai.add("Aikainen lintu madon nappaa. ");
        this.ai.add("Aikainen lintu ehkä madon nappaa, mutta iltapäivällä väsähtää.");
        this.ai.add("Kell onni on, se onnen kätkeköön. ");
        this.ai.add("Kell onni on, se kernaasti iloitkoon.");
        this.ai.add("Laiska se töitänsä luettelee. ");
        this.ai.add("Fiksu se työnsä listaa ja niistä viestii.");
        this.ai.add("Raskas työ vaatii raskaat huvit. ");
        this.ai.add("Joka kuuseen kurkottaa, se katajaan kapsahtaa. ");
        this.ai.add("Joka ei tahdo töitä tehdä, sen ei syömänkään pidä. ");
        this.ai.add("Kissa se kiitoksella elää. ");
        this.ai.add("Kissa se kiitoksella elää – ja niin muuten ihminenkin.");

        this.ai.add("Jos menisin naimisiin, vaihtaisin miehen nimeen.");
        this.ai.add("Kait joku julkkis kirjallisuuden alalta");
        this.ai.add("Rakastuminen onneksi sekoittaa pään");
        this.ai.add("Intia, Nepal, Kiina, Amerikka");
        this.ai.add("Miljoona markkaa, kai sen vielä voi vaihtaa euroiksi?");
        this.ai.add("Mielenrauha");
        this.ai.add("Tyhjätasku");
        this.ai.add("Jaa-a!");
        this.ai.add("Kirje");
        this.ai.add("Se on katsojassa");
        this.ai.add("Tohelo");
        this.ai.add("Rehellisyys");
        this.ai.add("Ehkä laiskiaiseksi!");
        this.ai.add("Kaunista ja älykästä");
        this.ai.add("Kossua");
        this.ai.add("Auttamaan oikeaa kättä");
        this.ai.add("Reiluus?");
        this.ai.add("Rautaa");
        this.ai.add("Avioehto");
        this.ai.add("Aamukahvit");
        this.ai.add("Uskonto");
        this.ai.add("Kuunnella saman asian jankutusta");
        this.ai.add("Antaa anteeksi ja unohtaa");
        this.ai.add("Ei jatku itsekehuun");
        this.ai.add("Hellä kosketus");
        this.ai.add("Illallinen kotona");
        this.ai.add("Alastullessa");
        this.ai.add("Sydämen sivistystä");
        this.ai.add("On");
        this.ai.add("Lohi");
        this.ai.add("Kassakaappirosmo");
        this.ai.add("Kerran kuukaudessa");
        this.ai.add("En mihinkään");
        this.ai.add("Telkkarin");
        this.ai.add("Muumit");
        this.ai.add("Äkkiä sitten, ja kivuttomasti");
        this.ai.add("Kissa ja hiiri");
        this.ai.add("Hyvä tilannehuumori");
        this.ai.add("Kultun sängyssä");
        this.ai.add("Öh.. johonkin missä ei olisi talvea");
        this.ai.add("Gulp, ampumalla salaa");
        this.ai.add("Mustekynä");
        this.ai.add("Antiikin Kreikkaan");
        this.ai.add("v. 4000");
        this.ai.add("Toivo");
        this.ai.add("Suku");
        this.ai.add("Pieni pelko aina aloittaako se uudestaan, joutuuko itse mukaan ja ympäristön paheksunta");
        this.ai.add("Nadirin aaria Helmenkalastajista");
        this.ai.add("Ei sellaista ole");
        this.ai.add("No vaikka violetteja");
        this.ai.add("Bush");
        this.ai.add("Humalan tunne on kyllä mukava");
        this.ai.add("Jäävät auton alle");
        this.ai.add("Perhonen");
        this.ai.add("Kypros");
        this.ai.add("En mitään erikoista");
        this.ai.add("Tietsika");
        this.ai.add("Marimba");
        this.ai.add("Härkätaistelu");
        this.ai.add("Suru");
        this.ai.add("Ruoho");
        this.ai.add("Bussi");
        this.ai.add("Käteinen");
        this.ai.add("Miksi ei?");
        this.ai.add("Kylppärin seinän");
        this.ai.add("Itsesuojelu");
        this.ai.add("Vuosituhannen vaihtuminen");
        this.ai.add("Apinasta");
        this.ai.add("Halata");
        this.ai.add("Ei mikään, vaikka ne tulevat sieltä");
        this.ai.add("Paras paikka");
        this.ai.add("Hyvä turva");
        this.ai.add("Antibiootit");
        this.ai.add("Atomipommi");
        this.ai.add("Jos jokin on liian hyvää ollakseen totta, se usein myös on sitä");
        this.ai.add("Hiukan ruskettunut");
        this.ai.add("Uskon, onhan siitä esimerkkejä ympärillä");
        this.ai.add("Pasianssia");
        this.ai.add("Oikeasti ihminen, joka haluaa muille hyvää ja pystyy antamaan anteeksi, vaikka Äiti Teresa");
        this.ai.add("Ainahan ne unohtuu");
        this.ai.add("Kahvi");
        this.ai.add("En ole vielä kuullut");
        this.ai.add("Pettää luottamus");
        this.ai.add("Ostoslistan kotiin");
        this.ai.add("Häh? Kai niitä muutama tuli");
        this.ai.add("Kaiken keskellä");
        this.ai.add("Riippuu laadusta, mutta minttusuklaa maistuu ensin makealle, sitten kirpeän raikkaalle");
        this.ai.add("Käyttöväline");
        this.ai.add("Blues");
        this.ai.add("On sitä tullut pari kertaa valehdeltua..");
        this.ai.add("Sellainen josta ei jää kiinni");
        this.ai.add("Ei aavistustakaan");
        this.ai.add("Tasapaino");
        this.ai.add("Käynyt kuussa");
        this.ai.add("Pieni paikka, jossa ei ole mitään virikkeitä, ja johon ei juuri muuta ulkopuolelta ketään");
        this.ai.add("Pyöreä");
        this.ai.add("Helsingin saariston kesällä");
        this.ai.add("Vain muutaman");
        this.ai.add("Tämä oli ihan mukava");
        this.ai.add("Lauantaina");
        this.ai.add("En haluis");
        this.ai.add("Laulaja");
        this.ai.add("Viina x)");
        this.ai.add("Hawaiji,Espanja,Kreikka,Turkki");
        this.ai.add("10 000 euroo...");
        this.ai.add("Elää täysil loppuu saakka x)");
        this.ai.add("Rakastettu tyhjätaku");
        this.ai.add("Saari meren keskellä");
        this.ai.add("Tekstari");
        this.ai.add("Ulkonäkö (????) xD");
        this.ai.add("Idioootti");
        this.ai.add("Rehellisyys");
        this.ai.add("Kissaks");
        this.ai.add("Luonnollisen kaunista ihmistä...");
        this.ai.add("Siideriä");
        this.ai.add("Kantamiseen,halaamiseen jne. x)");
        this.ai.add("Peukalo x)");
        this.ai.add("Täyttä kultaa");
        this.ai.add("Ethän koskaan petä mua? x)");
        this.ai.add("Voitko siirtyy makuuhuoneen puolelle? x)");
        this.ai.add("Myrkky.... xD Mä en oikee tajunnu tota..");
        this.ai.add("Odottaminen");
        this.ai.add("Se et rakkaus ei koskaa \"sammu\"");
        this.ai.add("Navan alapuolella xD");
        this.ai.add("Halaus :)");
        this.ai.add("Romanttinen kynttiläillallinen kotona..");
        this.ai.add("Vaikee sanoo :D");
        this.ai.add("Että voi kans puhuu siit asiast jonka ymmärtää xD");
        this.ai.add("On sil jonku verran");
        this.ai.add("Hauki");
        this.ai.add("Myymälävaras x)");
        this.ai.add("Kerran viikossa");
        this.ai.add("Napaan");
        this.ai.add("Tietokoneen xD");
        this.ai.add("Muumit");
        this.ai.add("\"Elkää tappakko minnuu\" xD");
        this.ai.add("Elefantti ja hiiri");
        this.ai.add("Kehuminen");
        this.ai.add("Sängyssä ois iha kiva.... XD");
        this.ai.add("Ruotsiin (se on lähempänä xD )");
        this.ai.add("Ampuisin aseella");
        this.ai.add("Kuulakärkikynä");
        this.ai.add("1970-80-lukuun amerikkaa xD");
        this.ai.add("vuoteen 3000");
        this.ai.add("rakkaus");
        this.ai.add("Ei tietookaa :D");
        this.ai.add("Se voi joutuu vankilaan, joutuisin tekemisiin rikollisen kans, muaki voitas syyttää jostain..");
        this.ai.add("First love");
        this.ai.add("Dragoste din tei... *oksentaa*");
        this.ai.add("Mustat");
        this.ai.add("Bush x)");
        this.ai.add("Ei ois muutakaa...");
        this.ai.add("a) kissat jää auton alle");
        this.ai.add("perhonen");
        this.ai.add("Sateinen päivä hawaijilla");
        this.ai.add("polttakoot rauhas");
        this.ai.add("tietsa");
        this.ai.add("Kitara");
        this.ai.add("Menkat x)");
        this.ai.add("Kuolema");
        this.ai.add("Nurmikko");
        this.ai.add("Bussi");
        this.ai.add("Käteisellä");
        this.ai.add("Muistuttaa suomee aika paljo");
        this.ai.add("Keittiön oven");
        this.ai.add("....");
        this.ai.add("Millenium,shamppanja x)");
        this.ai.add("Apinasta");
        this.ai.add("\"Hyvästi\"");
        this.ai.add("...");
        this.ai.add("..kullan kallis x)");
        this.ai.add("Oma omaisuus xD");
        this.ai.add("Sähkö");
        this.ai.add("ydinaseet yms.");
        this.ai.add("Sodassa ja rakkaudessa kaikki on sallittua");
        this.ai.add("Hiukan ruskettunut");
        this.ai.add("Uskon vaik rakkauden ei tartte kohdistuu poikaystävään tms... vaan esim. vanhempiin.");
        this.ai.add("Räsypokkaa");
        this.ai.add("häikäisevän kaunis,valkoset vaatteet/hiukset");
        this.ai.add("Käveleminen x)");
        this.ai.add("Vesi");
        this.ai.add("ei tuu mieleen");
        this.ai.add("Viedä jonkun poikaystävä");
        this.ai.add("Siivoominen x)");
        this.ai.add("En jaksa :D");
        this.ai.add("Keskellä ei mitään");
        this.ai.add("Hyvältä..");
        this.ai.add("raha on kahisevaa xD");
        this.ai.add("Iskelmä");
        this.ai.add("En muista xD");
        this.ai.add("Semmone joho uskotaa x)");
        this.ai.add("No ne aattelee et ihminen voi syntyy uudestaa sinä eläimenä.... *viisas* :D");
        this.ai.add("Näköaisti");
        this.ai.add("Tehny itellee keisarileikkauksen :S");
        this.ai.add("Ei kauppoja lähel,vähän taloja,peltoa...");
        this.ai.add("Pyöreä");
        this.ai.add("Jakomäen xD (sais nähä millast meininkii siel on xD )");
        this.ai.add("En ollenkaa.... xD");
        this.ai.add("Kivaa ajanvietettä x)");
        this.ai.add("Tiistai");

    }

    @Override
    public String toString() {
        return "Comment{" +
                "ai=" + ai +
                '}';
    }
}
